### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jonmsherman** [damikun/hotchocolate-mutation-errors#1]
Is it possible to implement this without CQRS? I'm not sure how to do the fluent validation in the regular middleware pipeline with GraphQL

**Comment by damikun** [comment]
It is but it require your time to rewrite the abstraction to the middleware...

Depends on project complexity and needs you usually select where you wanna handle errors, validation and auth. The recommended way is to keep minimal the authorization out from GraphQL because you can lost really fast ability to track if the graph is covered from all sides (travers security issue) another problem is problematic testing if you connect all with GraphQL..

This example was about error handling including validation and authorization... in general this are 3 concepts...

If you wanna do just validation there are few external libs. For example from Ben the "fairybread" you can search for it... Fairybread provides the abstraction and use middleware to do the validation job but is only for input validation no error handling and no authorization...
